Repository HumanSignal/label-studio-sdk, pull requests merged in 2024-06, with the labels that each got.

#227 fix: Migrate ls to migrate: set labeling config for the new_project
  examples/migrate_ls_to_ls/migrate-ls-to-ls.py
Labels: fix

#228 docs: Update README.md for migrate-ls-to-ls
  examples/migrate_ls_to_ls/README.md
Labels: docs

#229 ci: PLT-375: Support Poetry release
  .github/workflows/build_pypi.yml
  .github/workflows/release-set-version.yml
  .github/workflows/tests.yml
Labels: ci

#240 fix: RND-96: Fix circular imports by moving objects.py
  src/label_studio_sdk/label_interface/interface.py
  src/label_studio_sdk/label_interface/objects.py
  tests/custom/test_interface/test_compat.py
  tests/custom/test_interface/test_main.py
  tests/custom/test_interface/test_validation.py
  tests/custom/test_interface/test_value_objects.py
Labels: fix

#241 ci: Update CODEOWNERS
  .github/CODEOWNERS
Labels: ci

#242 fix: RND-96: Replace serialize() with pydantic field_serializer
  src/label_studio_sdk/label_interface/objects.py
  tests/custom/test_interface/test_value_objects.py
Labels: fix

#249 docs: Update README.md
  examples/migrate_ls_to_ls/README.md
Labels: docs
