Repository HumanSignal/label-studio-sdk, pull requests merged in 2024-03, with the labels that each got.

#187 feat: New labeling config parser
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  deploy.py
  examples/active_learning/active_learning.py
  examples/annotate_data_from_gcs/annotate_data_from_gcs.py
  examples/export_snapshots.py
  examples/import_preannotations/import_brush_predictions.py
  examples/import_preannotations/import_preannotations.py
  examples/label_studio_enterprise/assigner.py
  examples/migrate_ls_to_ls/migrate-ls-to-ls.py
  examples/weak_supervision/weak_supervision.py
  label_studio_sdk/__init__.py
  label_studio_sdk/client.py
  label_studio_sdk/data_manager.py
  label_studio_sdk/exceptions.py
  label_studio_sdk/label_interface/__init__.py
  label_studio_sdk/label_interface/base.py
  label_studio_sdk/label_interface/control_tags.py
  label_studio_sdk/label_interface/data_examples.json
  label_studio_sdk/label_interface/interface.py
  label_studio_sdk/label_interface/label_tags.py
  label_studio_sdk/label_interface/object_tags.py
  label_studio_sdk/label_interface/region.py
  label_studio_sdk/objects.py
  label_studio_sdk/project.py
  label_studio_sdk/schema/label_config_schema.json
  label_studio_sdk/users.py
  label_studio_sdk/utils.py
  label_studio_sdk/workspaces.py
  requirements.txt
  setup.py
  tests/test_client.py
  tests/test_interface/__init__.py
  tests/test_interface/configs.py
  tests/test_interface/mockups.py
  tests/test_interface/test_compat.py
  tests/test_interface/test_control_tags.py
  tests/test_interface/test_data_generation.py
  tests/test_interface/test_lpi.py
  tests/test_interface/test_main.py
  tests/test_interface/test_object_tags.py
  tests/test_interface/test_region.py
  tests/test_interface/test_validate_summary.py
  tests/test_interface/test_validation.py
Labels: feat

#161 docs: link fix and PR naming section
  CONTRIBUTING.md
  README.md
Labels: docs

#104 Add log level control to SDK
  label_studio_sdk/client.py
  label_studio_sdk/project.py
Labels: title needs formatting

#146 fix: Adding check for invalid Client instantiation
  label_studio_sdk/client.py
Labels: fix

#165 feat: Add default storage for migration script
  examples/migrate_ls_to_ls/migrate-ls-to-ls.py
Labels: feat

#184 fixes for pydantic v2
  label_studio_sdk/users.py
  label_studio_sdk/workspaces.py
Labels: title needs formatting

#189 feat: Add example on how to randomly assign tasks to reviewer
  examples/label_studio_enterprise/assign_10_percent_of_tasks.py
  label_studio_sdk/data_manager.py
Labels: feat

#188 feat: Add AWS S3 IAM import storage connection
  label_studio_sdk/project.py
Labels: feat

#190 feat: Add more storage endpoints. Add custom timeout to make request
  examples/cloud_storages/cloud_storage_guide.ipynb
  examples/migrate_ls_to_ls/migrate-ls-to-ls.py
  label_studio_sdk/__init__.py
  label_studio_sdk/client.py
  label_studio_sdk/project.py
Labels: feat

#196 fix: version parsing in setup.py
  setup.py
Labels: fix

#193 fix missing import
  label_studio_sdk/label_interface/interface.py
Labels: title needs formatting

#191 fix: Excluding docs from setuptools
  setup.py
Labels: fix
