Repository HumanSignal/label-studio-sdk, pull requests merged in 2024-07, with the labels that each got.

#256 docs: Update commands in version section
  README.md
Labels: docs

#248 feat: RND-100: Labeling interface enhancements
  src/label_studio_sdk/label_interface/base.py
  src/label_studio_sdk/label_interface/create.py
  src/label_studio_sdk/label_interface/interface.py
  tests/custom/test_interface/test_create.py
Labels: feat

#264 fix: RND-103: add workspace.is_archived
  .mock/definition/workspaces.yml
  README.md
  poetry.lock
  reference.md
  src/label_studio_sdk/workspaces/client.py
Labels: fix

#265 docs: Update README to include HumanSignal URL
  examples/migrate_ls_to_ls/README.md
Labels: docs
