Repository HumanSignal/label-studio-sdk, pull requests merged in 2024-09, with the labels that each got.

#306 feat: DIA-1422: Add model provider connection to prompt version
  .mock/definition/__package__.yml
  .mock/definition/prompts/versions.yml
  poetry.lock
  reference.md
  src/label_studio_sdk/prompts/versions/client.py
  src/label_studio_sdk/types/prompt_version.py
  tests/prompts/test_versions.py
Labels: feat

#314 fix: Fix download_and_cache for local storage with files in the root dir
  src/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py
Labels: fix

#313 feat: DIA-1410: Add support for list of str for multilabel
  src/label_studio_sdk/label_interface/interface.py
Labels: feat

#316 feat: DIA-1410: Multi label text classification
  src/label_studio_sdk/label_interface/interface.py
Labels: feat

#283 fix: Revert APACHE license back
  LICENSE
Labels: fix

#317 fix: Skip webhook patch tests, temporary comment lint
  .github/workflows/lint.yml
  src/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py
  tests/test_webhooks.py
Labels: fix

#323 docs: Add notes about old version in examples
  examples/active_learning/active_learning.ipynb
  examples/active_learning/active_learning.py
  examples/adding_new_labels_to_project.ipynb
  examples/annotate_data_from_gcs/annotate_data_from_gcs.py
  examples/cloud_storages/cloud_storage_guide.ipynb
  examples/export_snapshots.py
  examples/export_with_filters.py
  examples/import_preannotations/import_brush_predictions.py
  examples/import_preannotations/import_preannotations.py
  examples/label_studio_enterprise/assign_10_percent_of_tasks.py
  examples/label_studio_enterprise/assigner.py
  examples/label_studio_enterprise/assignment.ipynb
  examples/label_studio_enterprise/user_management.ipynb
  examples/migrate_ls_to_ls/README.md
  examples/migrate_ls_to_ls/migrate-ls-to-ls.py
  examples/weak_supervision/weak_supervision.ipynb
  examples/weak_supervision/weak_supervision.py
Labels: docs
