Repository HumanSignal/label-studio-sdk, pull requests merged in 2024-08, with the labels that each got.

#268 docs: Fix import Client command
  README.md
Labels: docs

#272 chore: LEAP-1365: Bump NLTK to address CVE
  poetry.lock
  pyproject.toml
Labels: chore

#276 fix: Getting started ipynb
  examples/getting_started.ipynb
Labels: fix

#251 fix: Import multiple segmentations from coco format json
  src/label_studio_sdk/converter/imports/coco.py
  tests/custom/converter/data/test_import_coco/coco_import_input.json
  tests/custom/converter/test_import_coco.py
Labels: fix

#290 fix: LEAP-1339: Disable YOLO_OBB for timeline labels
  src/label_studio_sdk/converter/converter.py
Labels: fix

#295 feat: RND-116: Add convert_yolo_obb_to_annotation to utils for YOLO ML backend
  src/label_studio_sdk/converter/utils.py
  tests/custom/converter/test_export_yolo.py
Labels: feat
