Repository HumanSignal/label-studio-sdk, pull requests merged in 2025-04, with the labels that each got.

#437 ci: Remove obsolete FM v1
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#441 fix: DIA-2051: Jinja2 security vulnerability
  poetry.lock
  pyproject.toml
Labels: fix

#429 feat: LEAP-1937: Add brush_to_coco format
  poetry.lock
  pyproject.toml
  src/label_studio_sdk/converter/converter.py
  src/label_studio_sdk/converter/exports/brush_to_coco.py
  src/label_studio_sdk/converter/main.py
  tests/test_brush_to_coco.py
Labels: feat

#443 fix: LEAP-1842: Repair label-studio-converter cli
  pyproject.toml
Labels: fix

#436 chore: upgrade NumPy to 2.0
  examples/mensuration_and_polling/requirements.txt
  poetry.lock
  pyproject.toml
Labels: chore

#445 fix: LEAP-1937: Fix opencv dependency
  pyproject.toml
Labels: fix
