Repository HumanSignal/label-studio-sdk, pull requests merged in 2025-08, with the labels that each got.

#498 chore: ROOT-67: bump poetry to version that fixes virtualenv
  .github/workflows/build_pypi.yml
Labels: chore

#530 Add example script for managing user licenses
  examples/label_studio_enterprise/managing_user_licenses.py
Labels: title needs formatting

#537 feat: BROS-349: Add assign user and export snapshot tutorials
  tutorials/assign_users_to_tasks.py
  tutorials/export_snapshots.py
Labels: feat
